export enum GameOption {
  DungeonsRiddle = "DungeonsRiddle",
  HauntedMansion = "HauntedMansion",
  NorthWall = "NorthWall",
  SouthWall = "SouthWall",
  WestWall = "WestWall",
  EastWall = "EastWall",
  InspectDoor = "InspectDoor",
  UnlockDoor = "UnlockDoor",
  UseAmulet = "UseAmulet",
  InspectShelf = "InspectShelf",
  ReadBook = "ReadBook",
  InspectToolSet = "InspectToolSet",
  AttackGoblin = "AttackGoblin",
  AttackTroll = "AttackTroll",
  ActivateSwitch = "ActivateSwitch",
  AnswerRiddle = "AnswerRiddle",
  AnswerIce = "AnswerIce",
  AnswerFire = "AnswerFire",
  AnswerShadow = "AnswerShadow",
  AnswerTree = "AnswerTree",
  RunAway = "RunAway",
  GoBackToCenter = "GoBackToCenter",
  RollAgainstTroll = "RollAgainstTroll",
  RollAgainstGoblin = "RollAgainstGoblin",
  StartNewGame = "StartNewGame",
  InspectEastWall = "InspectEastWall",
  RunAwayRoll = "RunAwayRoll",
}

export const gameOptions = {
  [GameOption.DungeonsRiddle]: "The Dungeon's Riddle 🏰",
  [GameOption.HauntedMansion]: "Haunted Mansion",
  [GameOption.NorthWall]: "North Wall ⬆️",
  [GameOption.SouthWall]: "South Wall ⬇️",
  [GameOption.WestWall]: "West Wall ⬅️",
  [GameOption.EastWall]: "East Wall ➡️",
  [GameOption.InspectDoor]: "Inspect Door 🔍",
  [GameOption.UnlockDoor]: "Unlock Door 🗝️",
  [GameOption.UseAmulet]: "Use Amulet 📿",
  [GameOption.InspectShelf]: "Inspect Shelf 📚",
  [GameOption.ReadBook]: "Read Diary 📕",
  [GameOption.InspectToolSet]: "Inspect Tool Set ⚒️",
  [GameOption.AttackGoblin]: "Attack Goblin 👊",
  [GameOption.AttackTroll]: "Attack Troll 👊",
  [GameOption.ActivateSwitch]: "Activate Switch 🕹",
  [GameOption.AnswerRiddle]: "Solve Riddle ❓",
  [GameOption.RunAway]: "Run Away",
  [GameOption.GoBackToCenter]: "Go Back To Center",
  [GameOption.RollAgainstTroll]: "Roll Dice 🎲",
  [GameOption.RollAgainstGoblin]: "Roll Dice 🎲",
  [GameOption.StartNewGame]: "Play Again",
  [GameOption.InspectEastWall]: "Inspect Wall 🔍",
  [GameOption.AnswerFire]: "Fire 🔥",
  [GameOption.AnswerTree]: "Tree 🌲",
  [GameOption.AnswerShadow]: "Shadow 👥",
  [GameOption.AnswerIce]: "Ice 🧊",
  [GameOption.RunAwayRoll]: "Roll Dice 🎲",
};

export const NewGameOptions = {
  [GameOption.NorthWall]: { label: gameOptions[GameOption.NorthWall] },
  [GameOption.EastWall]: { label: gameOptions[GameOption.EastWall] },
  [GameOption.SouthWall]: { label: gameOptions[GameOption.SouthWall] },
  [GameOption.WestWall]: { label: gameOptions[GameOption.WestWall] },
};
